[workspace]
members = [ "apps", "octets_rev", "qlog", "quiceh" ]
exclude = [ "fuzz"]

[profile.bench]
debug = true

[profile.release]
debug = true

[profile.performance]
inherits = "release"
lto = "fat"
codegen-units = 1
incremental = false

